### ISSUE TITLE
is-ssh returns `true` for https URLs that specify a port

### ISSUE THREAD

**Issue by Mr-Wallet** [IonicaBizau/is-ssh#5]
For example `https://my-website.com:80/`. This is related to #4 since the issue is that the index of `@` is -1, while the index of `:` is positive.

This is bubbling up to `git-url-parse` saying that the URL's protocol is `ssh`.

**Comment by themadtitanmathos** [comment]
If you run `is-ssh` on the new version (1.3.3) with `https://www.my-website/com:80` (no trailing slash) it still returns `true`.
I think the `RegEx` that was added is being too strict with requiring a trailing slash, but I could be wrong.
It might be a good idea to add that case to the tests as well.
